### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by vsqq0** [Yuu6883/MarkovJuniorWeb#3]
run npm install
run npm start
i get a error 
ERROR in ./src/web/index.tsx
Module build failed (from ./node_modules/_swc-loader@0.2.3@swc-loader/src/index.js):
Error: Cannot find module '@swc/core'

**Comment by Yuu6883** [comment]
`npm i @swc/core`
I'm not sure why swc-loader includes that dependency on linux but not on windows? GH action auto build works fine
