### ISSUE TITLE
I made a compatible "Random" of the C# in TypeCrsipt

### ISSUE THREAD

**Issue by x2nie** [Yuu6883/MarkovJuniorWeb#5]
Hi Yuu, 
I wonder if we can generate an identical result with MarkovJunior C#.
So I translated the C# (or dotnet) random function into TypeScript.
After a week stabilizing, I got the perfect result.

That was a good news, right? I think so.
THe bad news is, I did it in very old commit of your MarkovJuniorWeb: while it has no webassembly at all.
So here I send you only file that declare the random function.
(if you want to try, here is my [working branch](https://github.com/x2nie/markovjuniorweb/tree/x2nie-nowasm2))

Okay, here is the file: https://github.com/x2nie/MarkovJuniorWeb/blob/x2nie-nowasm2/src/random.ts

**Comment by x2nie** [comment]
YOu might ask, why this guy didn't send a pool request?
Well, There is another argue (beside it written in old commit), 
That is because my usage of this new random is dirty.
For example, it is still called as `rng.NextDouble`, like as the C# original code;  which it might be better written as `random.nextDouble` as more convenient for JS users.
(as same as the `.Next()` shall be written as `.next()` )
(and I let it be your todo, perhaps, for fun?).
However, I guarantee that is will give a verbatim result in JS/TypeScript, compared to the one generated by C#.

**Comment by x2nie** [comment]
Oh, I forgot to mention.. How I am sure that it will generates an identical result?
answer: by allow user to manually input the `seed`. 

So, let say we give the MarkovJuniorC# : `<model name="BasicKey" seed="1234567" />`
then we input that same seed into the MarkovJunioWeb. 
That is just that is that.

**Comment by Yuu6883** [comment]
Feel free to just PR this, I can't care less about naming conventions 😂

**Comment by x2nie** [comment]
Yeah, I made a PR: #7

**Comment by x2nie** [comment]
Yeah, I just made that !
#7
